In [2]:
import numpy as np
alist=[1,2,3,4,5] #list
narray=np.array([1,2,3,4]) #array
print(alist)
print(narray)
print(type(alist))
print(type(narray))

[1, 2, 3, 4, 5]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>


In [3]:
print(narray + narray) #adds two vectors with same dimension
print(alist + alist) #concatenates two lists
print(narray * 3) #multiplies each element of array with 3
print(alist * 3) #concatenates the list 3 times

[2 4 6 8]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 3  6  9 12]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [4]:
npmatrix=np.array([narray,narray,narray]) #creates a 3x4 matrix
npmatrix2=np.array([alist,alist,alist]) #creates a 3x5 matrix
print(npmatrix)
print(npmatrix2)
"""Always make sure that the rows have the same number of elements"""

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


'Always make sure that the rows have the same number of elements'

In [5]:
print(npmatrix.shape) #prints the shape of the matrix
print(npmatrix2.shape) #prints the shape of the matrix
print(npmatrix*3)

(3, 4)
(3, 5)
[[ 3  6  9 12]
 [ 3  6  9 12]
 [ 3  6  9 12]]


In [6]:
print(npmatrix*npmatrix) #element wise multiplication

[[ 1  4  9 16]
 [ 1  4  9 16]
 [ 1  4  9 16]]


In [7]:
matrix3x4=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
t_matrix3x4=matrix3x4.T #transpose of the matrix
print(t_matrix3x4)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [8]:
nparray1=np.array([1,2,3,4])
norm1=np.linalg.norm(nparray1) #calculates the norm of the vector
print(norm1)
nparray2=np.array([[1,2],[3,4]]) 
norm2=np.linalg.norm(nparray2) # without another parameter it calculates the norm as an array
print(norm2)
normbyCols=np.linalg.norm(nparray2,axis=0) #calculates the norm of the columns
normbyRows=np.linalg.norm(nparray2,axis=1) #calculates the norm of the rows
print(normbyCols)
print(normbyRows)

5.477225575051661
5.477225575051661
[3.16227766 4.47213595]
[2.23606798 5.        ]


In [9]:
#THE DOT PRODUCT
nparray1=np.array([0,1,2,3])
nparray2=np.array([4,5,6,7])
dotproduct=np.dot(nparray1,nparray2) #dot product of two vectors
print(dotproduct)

38


In [10]:
nparray2=np.array([[1,2],[3,4]])
sumbycol=np.sum(nparray2,axis=0) #sum of the columns
sumbyrow=np.sum(nparray2,axis=1) #sum of the rows
print(sumbycol)
print(sumbyrow)
narray_centered=nparray2-np.mean(nparray2,axis=0) #centering the matrix
print(narray_centered)
#for row centered matrix
narray_centered=nparray2.T-np.mean(nparray2,axis=1) #centering the matrix
print(narray_centered.T)

[4 6]
[3 7]
[[-1. -1.]
 [ 1.  1.]]
[[-0.5  0.5]
 [-0.5  0.5]]
